x-user-args: &user-args
  USER_ID: ${USER_ID:-$(id -u)}
  GROUP_ID: ${GROUP_ID:-$(id -g)}
  USER_NAME: ${USER_NAME:-$(whoami)}
  GROUP_NAME: ${GROUP_NAME:-$(id -gn)}
  PASSWORD: ${PASSWORD:-MoBio888}
  ROOT_PASSWORD: ${ROOT_PASSWORD:-MoBio888}
  ROOT: ${ROOT:-TRUE}

services:
  dev:
    # user: ${USER_NAME:-$(whoami)}
    image: ${DOCKER_MIRROR:-docker.io}/mobior:v0.0.1
    build:
      context: .
      args: 
        <<: *user-args
        DOCKER_MIRROR: ${DOCKER_MIRROR:-docker.io}
      dockerfile: Dockerfile
    environment:
      <<: *user-args
    ports:
      - "${PORT:-7878}:8787"
    working_dir: /home/${USER_NAME:-$(whoami)}  # 设置工作目录
    volumes:
      - .:/home/${USER_NAME:-$(whoami)}/analysis
      - ${R_SITE_LIBRARY:-/usr/local/lib/R/site-library}:/usr/local/lib/R/site-library
      # VS Code 相关目录的持久化
      - vscode-server:/home/${USER_NAME:-$(whoami)}/.vscode-server
      - vscode-extensions:/home/${USER_NAME:-$(whoami)}/.local/share/code-server/extensions
    container_name: rstudio_test

# 定义命名卷
volumes:
  vscode-server:
  vscode-extensions:
