x-user-args: &user-args
  USER_ID: ${USER_ID:-$(id -u)}
  GROUP_ID: ${GROUP_ID:-$(id -g)}
  USER_NAME: ${USER_NAME:-$(whoami)}
  GROUP_NAME: ${GROUP_NAME:-$(id -gn)}
  PASSWORD: ${PASSWORD:-MoBio888}
  ROOT_PASSWORD: ${ROOT_PASSWORD:-MoBio888}
  ROOT: ${ROOT:-TRUE}

services:
  dev:
    # user: ${USER_NAME:-$(whoami)}
    # user: ${USER_ID:-$(id -u)}:${GROUP_ID:-$(id -g)}  # 指定容器内的运行用户
    image: ${DOCKER_MIRROR:-docker.io}/mobior:v0.0.1
    build:
      context: .
      args: 
        <<: *user-args
        DOCKER_MIRROR: ${DOCKER_MIRROR:-docker.io}
      dockerfile: Dockerfile
    environment:
      <<: *user-args
      R_LIBS_USER: /usr/local/lib/R/site-library
      R_LIBS: /usr/local/lib/R/site-library
      # 添加以下环境变量控制RStudio登录
      USER: ${USER_NAME:-$(whoami)}
      DISABLE_AUTH: "false"
      # 如果希望自动登录，可以使用下面的设置（不推荐用于生产环境）
      # DISABLE_AUTH: "true"
    ports:
      - "${PORT:-7878}:8787"
    working_dir: /home/${USER_NAME:-$(whoami)}/analysis  # 设置工作目录
    volumes:
      - ${MOUNT_PATH}:/home/${USER_NAME:-$(whoami)}/analysis
      - ${R_SITE_LIBRARY:-/usr/local/lib/R/site-library}:/usr/local/lib/R/site-library
      # VS Code 相关目录的持久化
      - vscode-server:/home/${USER_NAME:-$(whoami)}/.vscode-server
      - vscode-extensions:/home/${USER_NAME:-$(whoami)}/.local/share/code-server/extensions
    container_name: rstudio_test

# 定义命名卷
volumes:
  vscode-server:
  vscode-extensions:
