name: 验证开发环境

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # 清理缓存
      - name: 清理 Docker 缓存
        run: |
          docker system prune -af
          docker builder prune -af
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          driver-opts: |
            image=moby/buildkit:latest
            network=host
      
      - uses: actions/checkout@v4
      
      - name: 验证开发环境
        run: |
          # 使用 --pull 确保获取最新的基础镜像
          docker compose pull
          # 使用 --no-cache 强制重新构建
          docker compose build --no-cache
          docker compose up -d
          docker compose ps
          docker compose down