name: 验证开发环境

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # 清理缓存
      - name: 清理 Docker 缓存
        run: |
          docker system prune -af
          docker builder prune -af
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - uses: actions/checkout@v4
      
      - name: 设置环境变量
        run: |
          echo "MOUNT_PATH=${PWD}" >> $GITHUB_ENV
          echo "USER_NAME=$(whoami)" >> $GITHUB_ENV
      
      - name: 验证开发环境
        run: |
          # 构建并启动，使用 --build 强制重新构建
          docker compose up -d --build
          docker compose ps
          docker compose down