name: 发布版本

on:
  push:
    tags:
      - 'v*'  # 触发条件：推送 v 开头的标签，如 v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 测试构建
      - name: 构建测试
        run: docker compose build
      
      # 测试环境
      - name: 测试环境可用性
        run: |
          docker compose up -d
          sleep 10
          curl -f http://localhost:7878 || exit 1
      
      # 创建 GitHub Release
      - name: 创建 Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            docker-compose.yml
            Dockerfile
            entrypoint.sh
          body: |
            ## R 开发环境 v${{ github.ref_name }}
            
            ### 包含组件
            - RStudio Server
            - 常用系统依赖
            - Rust 开发环境
            
            ### 使用方法
            
            1. 克隆仓库:
            ```bash
            git clone <repo-url>
            cd <repo-name>
            ```
            
            2. 启动环境:
            ```bash
            docker compose up -d
            ```
            
            ### 环境变量
            - USERNAME: 默认使用当前用户
            - USER_PASSWORD: RStudio 登录密码
            - ROOT_PASSWORD: root 密码
            
            ### 访问方式
            http://localhost:7878
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 